// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AuthFormTitle: typeof import('./src/components/auth/AuthFormTitle.vue')['default']
    BaseButton: typeof import('./src/components/UI/BaseButton.vue')['default']
    CurrencyIcon: typeof import('./src/components/expense/CurrencyIcon.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElTag: typeof import('element-plus/es')['ElTag']
    ExpenseItem: typeof import('./src/components/expense/ExpenseItem.vue')['default']
    ExpenseList: typeof import('./src/components/expense/ExpenseList.vue')['default']
    Footer: typeof import('./src/components/layout/Footer.vue')['default']
    Icon: typeof import('./src/components/UI/Icon.vue')['default']
    LoginForm: typeof import('./src/components/auth/LoginForm.vue')['default']
    NavBar: typeof import('./src/components/nav/NavBar.vue')['default']
    NavItem: typeof import('./src/components/nav/NavItem.vue')['default']
    NavMenu: typeof import('./src/components/nav/NavMenu.vue')['default']
    RegisterForm: typeof import('./src/components/auth/RegisterForm.vue')['default']
  }
}

export { }
