// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    BaseButton: typeof import('./src/components/UI/BaseButton.vue')['default']
    CurrencyIcon: typeof import('./src/components/expense/CurrencyIcon.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    ExpenseData: typeof import('./src/components/expense/ExpenseData.vue')['default']
    ExpenseForm: typeof import('./src/components/expense/ExpenseForm.vue')['default']
    ExpenseItemCard: typeof import('./src/components/expense/ExpenseItemCard.vue')['default']
    ExpenseList: typeof import('./src/components/expense/ExpenseList.vue')['default']
    Icon: typeof import('./src/components/UI/Icon.vue')['default']
    LoginForm: typeof import('./src/components/auth/LoginForm.vue')['default']
    NavBar: typeof import('./src/components/nav/NavBar.vue')['default']
    NavItem: typeof import('./src/components/nav/NavItem.vue')['default']
    PageTitle: typeof import('./src/components/UI/PageTitle.vue')['default']
    RegisterForm: typeof import('./src/components/auth/RegisterForm.vue')['default']
  }
}

export { }
