// Generated by https://quicktype.io

export interface ExchangeRateResponse {
  query: Query
  data: CurrencyRates
}

export interface Query {
  apikey: string
  base_currency: string
  timestamp: number
}

export type CurrencyRates = Record<string, number>

export enum Currency {
  USD = 'USD',
  EUR = 'EUR',
  GBP = 'GBP',
  BTC = 'BTC',
}
